site_name: My Docs
theme:
  name: material
  features:
    - search.suggest
    - search.highlight

plugins:
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: America/Sao_Paulo

markdown_extensions:
  - footnotes
