# Repository
site_name: Notes
repo_name: gabrielbdornas/notes
repo_url: https://github.com/gabrielbdornas/notes
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view

plugins:
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: America/Sao_Paulo
  - git-committers:
      repository: gabrielbdornas/notes
      branch: main
      enabled: !ENV ALLOW_GIT_COMMITTERS_BUILD
      token: !ENV ['GH_TOKEN']
  - mkdocs-video:
      video_muted: True
      video_controls: True
      video_autoplay: False

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - assets/style.css
extra_javascript:
  - assets/style.js
