name: Keep Render Alive

on:
  schedule:
    - cron: '*/14 * * * *'  # Run every 14 minutes
  workflow_dispatch:

jobs:
  keep_render_alive:
    runs-on: ubuntu-latest
    steps:
    - name: Send request to keep Render alive
      run: |
        curl -s -o /dev/null -w "%{http_code}" https://notes.braico.me/
    - name: Workflow failure notification
      uses: JasonEtco/create-an-issue@v2
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        filename: .github/workflow_keep_render_alive_failure.md
