name: Packages update

on:
  # Allow manual triggers.
  workflow_dispatch:
  # Automatically run once a week.
  schedule:
    - cron: "0 0 * * 1"

jobs:
  packages_update:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read Python and Poetry versions
        run: |
          echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
          echo "POETRY_VERSION=$(poetry --version | awk '{print $3}' | tr -d '()')" >> $GITHUB_ENV

      - name: Update Python packages
        uses: fuzzylabs/gha-poetry-update@v1
        with:
          base-branch: main
          poetry-version: ${{ env.POETRY_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run tests
        run: poetry run pytest

      - name: Workflow failure notification
        uses: JasonEtco/create-an-issue@v2
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RUNID: ${{ github.run_id }}
        with:
          filename: .github/workflow_packages_update_failure.md
